version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: inventoryapi:v1
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: admin1
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sa
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
      ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_MONGODB_URL: mongodb://sa:admin1@mongodb
      # ME_CONFIG_MONGODB_URL: mongodb://sa:admin1@mongodb:27017/
volumes:
  mongodb-data:
    driver: local
